name: MandelbotShader
description: Try to calc on GPU
dependencies:
  browser: any
  collection: any
#  datgui: any
  stats:
    git: https://github.com/Dartist/stats.dart.git
  tweenengine: any
dev_dependencies:
  unittest: any
